language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x gradlew

#Travic CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOEM/.gradle'

script: "./gradlew clean build"

#CI 실행 완료시 메일로 알람
notifications: 
  email:
    recipients:
      - min950903@naver.com
